/*
 * This file is generated by jOOQ.
 */
package com.zornflow.infrastructure.persistence.jooq.tables.records;


import com.zornflow.infrastructure.persistence.jooq.tables.ChainNodes;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;


/**
 * 节点在链中的具体实例，存储顺序、与共享模板的链接以及属性覆盖
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ChainNodesRecord extends UpdatableRecordImpl<ChainNodesRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Create a detached ChainNodesRecord
   */
  public ChainNodesRecord() {
    super(ChainNodes.CHAIN_NODES);
  }

  /**
   * Create a detached, initialised ChainNodesRecord
   */
  public ChainNodesRecord(String id, String processChainId, String sharedNodeId, Integer sequence, String name, String nextNodeId, String nodeType, String ruleChainId, JSONB conditions, JSONB properties, Integer version, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
    super(ChainNodes.CHAIN_NODES);

    setId(id);
    setProcessChainId(processChainId);
    setSharedNodeId(sharedNodeId);
    setSequence(sequence);
    setName(name);
    setNextNodeId(nextNodeId);
    setNodeType(nodeType);
    setRuleChainId(ruleChainId);
    setConditions(conditions);
    setProperties(properties);
    setVersion(version);
    setCreatedAt(createdAt);
    setUpdatedAt(updatedAt);
    resetTouchedOnNotNull();
  }

  /**
   * Create a detached, initialised ChainNodesRecord
   */
  public ChainNodesRecord(com.zornflow.infrastructure.persistence.jooq.tables.pojos.ChainNodes value) {
    super(ChainNodes.CHAIN_NODES);

    if (value != null) {
      setId(value.getId());
      setProcessChainId(value.getProcessChainId());
      setSharedNodeId(value.getSharedNodeId());
      setSequence(value.getSequence());
      setName(value.getName());
      setNextNodeId(value.getNextNodeId());
      setNodeType(value.getNodeType());
      setRuleChainId(value.getRuleChainId());
      setConditions(value.getConditions());
      setProperties(value.getProperties());
      setVersion(value.getVersion());
      setCreatedAt(value.getCreatedAt());
      setUpdatedAt(value.getUpdatedAt());
      resetTouchedOnNotNull();
    }
  }

  /**
   * Getter for <code>engine.chain_nodes.id</code>.
   */
  public String getId() {
    return (String) get(0);
  }

  /**
   * Setter for <code>engine.chain_nodes.id</code>.
   */
  public ChainNodesRecord setId(String value) {
    set(0, value);
    return this;
  }

  /**
   * Getter for <code>engine.chain_nodes.process_chain_id</code>.
   */
  public String getProcessChainId() {
    return (String) get(1);
  }

  /**
   * Setter for <code>engine.chain_nodes.process_chain_id</code>.
   */
  public ChainNodesRecord setProcessChainId(String value) {
    set(1, value);
    return this;
  }

  /**
   * Getter for <code>engine.chain_nodes.shared_node_id</code>.
   */
  public String getSharedNodeId() {
    return (String) get(2);
  }

  /**
   * Setter for <code>engine.chain_nodes.shared_node_id</code>.
   */
  public ChainNodesRecord setSharedNodeId(String value) {
    set(2, value);
    return this;
  }

  /**
   * Getter for <code>engine.chain_nodes.sequence</code>.
   */
  public Integer getSequence() {
    return (Integer) get(3);
  }

  /**
   * Setter for <code>engine.chain_nodes.sequence</code>.
   */
  public ChainNodesRecord setSequence(Integer value) {
    set(3, value);
    return this;
  }

  /**
   * Getter for <code>engine.chain_nodes.name</code>.
   */
  public String getName() {
    return (String) get(4);
  }

  /**
   * Setter for <code>engine.chain_nodes.name</code>.
   */
  public ChainNodesRecord setName(String value) {
    set(4, value);
    return this;
  }

  /**
   * Getter for <code>engine.chain_nodes.next_node_id</code>.
   */
  public String getNextNodeId() {
    return (String) get(5);
  }

  /**
   * Setter for <code>engine.chain_nodes.next_node_id</code>.
   */
  public ChainNodesRecord setNextNodeId(String value) {
    set(5, value);
    return this;
  }

  /**
   * Getter for <code>engine.chain_nodes.node_type</code>.
   */
  public String getNodeType() {
    return (String) get(6);
  }

  /**
   * Setter for <code>engine.chain_nodes.node_type</code>.
   */
  public ChainNodesRecord setNodeType(String value) {
    set(6, value);
    return this;
  }

  /**
   * Getter for <code>engine.chain_nodes.rule_chain_id</code>.
   */
  public String getRuleChainId() {
    return (String) get(7);
  }

  /**
   * Setter for <code>engine.chain_nodes.rule_chain_id</code>.
   */
  public ChainNodesRecord setRuleChainId(String value) {
    set(7, value);
    return this;
  }

  /**
   * Getter for <code>engine.chain_nodes.conditions</code>.
   */
  public JSONB getConditions() {
    return (JSONB) get(8);
  }

  /**
   * Setter for <code>engine.chain_nodes.conditions</code>.
   */
  public ChainNodesRecord setConditions(JSONB value) {
    set(8, value);
    return this;
  }

  /**
   * Getter for <code>engine.chain_nodes.properties</code>.
   */
  public JSONB getProperties() {
    return (JSONB) get(9);
  }

  /**
   * Setter for <code>engine.chain_nodes.properties</code>.
   */
  public ChainNodesRecord setProperties(JSONB value) {
    set(9, value);
    return this;
  }

  /**
   * Getter for <code>engine.chain_nodes.version</code>.
   */
  public Integer getVersion() {
    return (Integer) get(10);
  }

  /**
   * Setter for <code>engine.chain_nodes.version</code>.
   */
  public ChainNodesRecord setVersion(Integer value) {
    set(10, value);
    return this;
  }

  /**
   * Getter for <code>engine.chain_nodes.created_at</code>.
   */
  public OffsetDateTime getCreatedAt() {
    return (OffsetDateTime) get(11);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * Setter for <code>engine.chain_nodes.created_at</code>.
   */
  public ChainNodesRecord setCreatedAt(OffsetDateTime value) {
    set(11, value);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Getter for <code>engine.chain_nodes.updated_at</code>.
   */
  public OffsetDateTime getUpdatedAt() {
    return (OffsetDateTime) get(12);
  }

  /**
   * Setter for <code>engine.chain_nodes.updated_at</code>.
   */
  public ChainNodesRecord setUpdatedAt(OffsetDateTime value) {
    set(12, value);
    return this;
  }

  @Override
  public Record1<String> key() {
    return (Record1) super.key();
  }
}
