/*
 * This file is generated by jOOQ.
 */
package com.zornflow.infrastructure.persistence.jooq.tables.records;


import com.zornflow.infrastructure.persistence.jooq.tables.ProcessInstances;

import java.time.OffsetDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 流程实例
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ProcessInstancesRecord extends UpdatableRecordImpl<ProcessInstancesRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>engine.process_instances.id</code>.
     */
    public ProcessInstancesRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>engine.process_instances.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>engine.process_instances.process_chain_id</code>.
     */
    public ProcessInstancesRecord setProcessChainId(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>engine.process_instances.process_chain_id</code>.
     */
    public String getProcessChainId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>engine.process_instances.status</code>.
     */
    public ProcessInstancesRecord setStatus(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>engine.process_instances.status</code>.
     */
    public String getStatus() {
        return (String) get(2);
    }

    /**
     * Setter for <code>engine.process_instances.current_node_id</code>.
     */
    public ProcessInstancesRecord setCurrentNodeId(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>engine.process_instances.current_node_id</code>.
     */
    public String getCurrentNodeId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>engine.process_instances.context</code>.
     */
    public ProcessInstancesRecord setContext(JSONB value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>engine.process_instances.context</code>.
     */
    public JSONB getContext() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>engine.process_instances.version</code>.
     */
    public ProcessInstancesRecord setVersion(Integer value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>engine.process_instances.version</code>.
     */
    public Integer getVersion() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>engine.process_instances.created_at</code>.
     */
    public ProcessInstancesRecord setCreatedAt(OffsetDateTime value) {
        set(6, value);
        return this;
    }

    /**
     * Getter for <code>engine.process_instances.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(6);
    }

    /**
     * Setter for <code>engine.process_instances.updated_at</code>.
     */
    public ProcessInstancesRecord setUpdatedAt(OffsetDateTime value) {
        set(7, value);
        return this;
    }

    /**
     * Getter for <code>engine.process_instances.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProcessInstancesRecord
     */
    public ProcessInstancesRecord() {
        super(ProcessInstances.PROCESS_INSTANCES);
    }

    /**
     * Create a detached, initialised ProcessInstancesRecord
     */
    public ProcessInstancesRecord(String id, String processChainId, String status, String currentNodeId, JSONB context, Integer version, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(ProcessInstances.PROCESS_INSTANCES);

        setId(id);
        setProcessChainId(processChainId);
        setStatus(status);
        setCurrentNodeId(currentNodeId);
        setContext(context);
        setVersion(version);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised ProcessInstancesRecord
     */
    public ProcessInstancesRecord(com.zornflow.infrastructure.persistence.jooq.tables.pojos.ProcessInstances value) {
        super(ProcessInstances.PROCESS_INSTANCES);

        if (value != null) {
            setId(value.getId());
            setProcessChainId(value.getProcessChainId());
            setStatus(value.getStatus());
            setCurrentNodeId(value.getCurrentNodeId());
            setContext(value.getContext());
            setVersion(value.getVersion());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
