/*
 * This file is generated by jOOQ.
 */
package com.zornflow.infrastructure.persistence.jooq.tables.records;


import com.zornflow.infrastructure.persistence.jooq.tables.ProcessChains;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import java.time.OffsetDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ProcessChainsRecord extends UpdatableRecordImpl<ProcessChainsRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * Create a detached ProcessChainsRecord
   */
  public ProcessChainsRecord() {
    super(ProcessChains.PROCESS_CHAINS);
  }

  /**
   * Create a detached, initialised ProcessChainsRecord
   */
  public ProcessChainsRecord(String id, String name, String description, String recordStatus, Integer version, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
    super(ProcessChains.PROCESS_CHAINS);

    setId(id);
    setName(name);
    setDescription(description);
    setRecordStatus(recordStatus);
    setVersion(version);
    setCreatedAt(createdAt);
    setUpdatedAt(updatedAt);
    resetTouchedOnNotNull();
  }

  /**
   * Create a detached, initialised ProcessChainsRecord
   */
  public ProcessChainsRecord(com.zornflow.infrastructure.persistence.jooq.tables.pojos.ProcessChains value) {
    super(ProcessChains.PROCESS_CHAINS);

    if (value != null) {
      setId(value.getId());
      setName(value.getName());
      setDescription(value.getDescription());
      setRecordStatus(value.getRecordStatus());
      setVersion(value.getVersion());
      setCreatedAt(value.getCreatedAt());
      setUpdatedAt(value.getUpdatedAt());
      resetTouchedOnNotNull();
    }
  }

  /**
   * Getter for <code>engine.process_chains.id</code>.
   */
  public String getId() {
    return (String) get(0);
  }

  /**
   * Setter for <code>engine.process_chains.id</code>.
   */
  public ProcessChainsRecord setId(String value) {
    set(0, value);
    return this;
  }

  /**
   * Getter for <code>engine.process_chains.name</code>.
   */
  public String getName() {
    return (String) get(1);
  }

  /**
   * Setter for <code>engine.process_chains.name</code>.
   */
  public ProcessChainsRecord setName(String value) {
    set(1, value);
    return this;
  }

  /**
   * Getter for <code>engine.process_chains.description</code>.
   */
  public String getDescription() {
    return (String) get(2);
  }

  /**
   * Setter for <code>engine.process_chains.description</code>.
   */
  public ProcessChainsRecord setDescription(String value) {
    set(2, value);
    return this;
  }

  /**
   * Getter for <code>engine.process_chains.record_status</code>.
   */
  public String getRecordStatus() {
    return (String) get(3);
  }

  /**
   * Setter for <code>engine.process_chains.record_status</code>.
   */
  public ProcessChainsRecord setRecordStatus(String value) {
    set(3, value);
    return this;
  }

  /**
   * Getter for <code>engine.process_chains.version</code>.
   */
  public Integer getVersion() {
    return (Integer) get(4);
  }

  /**
   * Setter for <code>engine.process_chains.version</code>.
   */
  public ProcessChainsRecord setVersion(Integer value) {
    set(4, value);
    return this;
  }

  /**
   * Getter for <code>engine.process_chains.created_at</code>.
   */
  public OffsetDateTime getCreatedAt() {
    return (OffsetDateTime) get(5);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  /**
   * Setter for <code>engine.process_chains.created_at</code>.
   */
  public ProcessChainsRecord setCreatedAt(OffsetDateTime value) {
    set(5, value);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /**
   * Getter for <code>engine.process_chains.updated_at</code>.
   */
  public OffsetDateTime getUpdatedAt() {
    return (OffsetDateTime) get(6);
  }

  /**
   * Setter for <code>engine.process_chains.updated_at</code>.
   */
  public ProcessChainsRecord setUpdatedAt(OffsetDateTime value) {
    set(6, value);
    return this;
  }

  @Override
  public Record1<String> key() {
    return (Record1) super.key();
  }
}
