/*
 * This file is generated by jOOQ.
 */
package com.zornflow.infrastructure.persistence.jooq.routines;


import com.zornflow.infrastructure.persistence.jooq.Engine;

import java.time.OffsetDateTime;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.DefaultDataType;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;



/**
 * @deprecated Unknown data type. If this is a qualified, user-defined type, it
 * may have been excluded from code generation. If this is a built-in type, you
 * can define an explicit {@link org.jooq.Binding} to specify how this type
 * should be handled. Deprecation can be turned off using {@literal
 * <deprecationOnUnknownTypes/>} in your code generator configuration.
 */
@Deprecated
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TimestamptzToUlid extends AbstractRoutine<Object> {

    private static final long serialVersionUID = 1L;

    /**
     * @deprecated Unknown data type. If this is a qualified, user-defined type,
     * it may have been excluded from code generation. If this is a built-in
     * type, you can define an explicit {@link org.jooq.Binding} to specify how
     * this type should be handled. Deprecation can be turned off using
     * {@literal <deprecationOnUnknownTypes/>} in your code generator
     * configuration.
     */
    @Deprecated
    public static final Parameter<Object> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", DefaultDataType.getDefaultDataType("\"engine\".\"ulid\""), false, false);

    /**
     * The parameter <code>engine.timestamptz_to_ulid.input</code>.
     */
    public static final Parameter<OffsetDateTime> INPUT = Internal.createParameter("input", SQLDataType.TIMESTAMPWITHTIMEZONE(6), false, false);

    /**
     * Create a new routine call instance
     */
    public TimestamptzToUlid() {
        super("timestamptz_to_ulid", Engine.ENGINE, DSL.comment(""), DefaultDataType.getDefaultDataType("\"engine\".\"ulid\""));

        setReturnParameter(RETURN_VALUE);
        addInParameter(INPUT);
    }

    /**
     * Set the <code>input</code> parameter IN value to the routine
     */
    public void setInput(OffsetDateTime value) {
        setValue(INPUT, value);
    }

    /**
     * Set the <code>input</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public TimestamptzToUlid setInput(Field<OffsetDateTime> field) {
        setField(INPUT, field);
        return this;
    }
}
