/*
 * This file is generated by jOOQ.
 */
package com.zornflow.infrastructure.persistence.jooq.routines;


import com.zornflow.infrastructure.persistence.jooq.Engine;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.*;

import java.time.LocalDateTime;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class UlidToTimestamp extends AbstractRoutine<LocalDateTime> {

  /**
   * The parameter <code>engine.ulid_to_timestamp.RETURN_VALUE</code>.
   */
  public static final Parameter<LocalDateTime> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.LOCALDATETIME(6), false, false);
  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static final Parameter<Object> INPUT = Internal.createParameter("input", DefaultDataType.getDefaultDataType("\"engine\".\"ulid\""), false, false);
  private static final long serialVersionUID = 1L;

  /**
   * Create a new routine call instance
   */
  public UlidToTimestamp() {
    super("ulid_to_timestamp", Engine.ENGINE, DSL.comment(""), SQLDataType.LOCALDATETIME(6));

    setReturnParameter(RETURN_VALUE);
    addInParameter(INPUT);
  }

  /**
   * Set the <code>input</code> parameter IN value to the routine
   */
  public void setInput(Object value) {
    setValue(INPUT, value);
  }

  /**
   * Set the <code>input</code> parameter to the function to be used with a
   * {@link org.jooq.Select} statement
   */
  public UlidToTimestamp setInput(Field<Object> field) {
    setField(INPUT, field);
    return this;
  }
}
