/*
 * This file is generated by jOOQ.
 */
package com.zornflow.infrastructure.persistence.jooq;


import org.jooq.Constants;
import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;

import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class DefaultCatalog extends CatalogImpl {

  /**
   * The reference instance of <code>DEFAULT_CATALOG</code>
   */
  public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();
  private static final long serialVersionUID = 1L;
  /**
   * A reference to the 3.20 minor release of the code generator. If this
   * doesn't compile, it's because the runtime library uses an older minor
   * release, namely: 3.20. You can turn off the generation of this reference
   * by specifying /configuration/generator/generate/jooqVersionReference
   */
  private static final String REQUIRE_RUNTIME_JOOQ_VERSION = Constants.VERSION_3_20;
  /**
   * The schema <code>engine</code>.
   */
  public final Engine ENGINE = Engine.ENGINE;

  /**
   * No further instances allowed
   */
  private DefaultCatalog() {
    super("");
  }

  @Override
  public final List<Schema> getSchemas() {
    return Arrays.asList(
      Engine.ENGINE
    );
  }
}
