/*
 * This file is generated by jOOQ.
 */
package com.zornflow.infrastructure.persistence.jooq;


import com.zornflow.infrastructure.persistence.jooq.tables.ChainNodes;
import com.zornflow.infrastructure.persistence.jooq.tables.ChainRules;
import com.zornflow.infrastructure.persistence.jooq.tables.ProcessInstances;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in engine.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Indexes {

  // -------------------------------------------------------------------------
  // INDEX definitions
  // -------------------------------------------------------------------------

  public static final Index IDX_CHAIN_NODES_PROCESS_CHAIN_ID = Internal.createIndex(DSL.name("idx_chain_nodes_process_chain_id"), ChainNodes.CHAIN_NODES, new OrderField[]{ChainNodes.CHAIN_NODES.PROCESS_CHAIN_ID}, false);
  public static final Index IDX_CHAIN_NODES_SHARED_NODE_ID = Internal.createIndex(DSL.name("idx_chain_nodes_shared_node_id"), ChainNodes.CHAIN_NODES, new OrderField[]{ChainNodes.CHAIN_NODES.SHARED_NODE_ID}, false);
  public static final Index IDX_CHAIN_RULES_RULE_CHAIN_ID = Internal.createIndex(DSL.name("idx_chain_rules_rule_chain_id"), ChainRules.CHAIN_RULES, new OrderField[]{ChainRules.CHAIN_RULES.RULE_CHAIN_ID}, false);
  public static final Index IDX_CHAIN_RULES_SHARED_RULE_ID = Internal.createIndex(DSL.name("idx_chain_rules_shared_rule_id"), ChainRules.CHAIN_RULES, new OrderField[]{ChainRules.CHAIN_RULES.SHARED_RULE_ID}, false);
  public static final Index IDX_PROCESS_INSTANCES_PROCESS_CHAIN_ID = Internal.createIndex(DSL.name("idx_process_instances_process_chain_id"), ProcessInstances.PROCESS_INSTANCES, new OrderField[]{ProcessInstances.PROCESS_INSTANCES.PROCESS_CHAIN_ID}, false);
  public static final Index IDX_PROCESS_INSTANCES_STATUS = Internal.createIndex(DSL.name("idx_process_instances_status"), ProcessInstances.PROCESS_INSTANCES, new OrderField[]{ProcessInstances.PROCESS_INSTANCES.STATUS}, false);
}
