/*
 * This file is generated by jOOQ.
 */
package com.zornflow.infrastructure.persistence.jooq;


import com.zornflow.infrastructure.persistence.jooq.routines.*;
import org.jooq.Configuration;
import org.jooq.Field;

import java.time.LocalDateTime;
import java.time.OffsetDateTime;
import java.util.UUID;


/**
 * Convenience access to all stored procedures and functions in engine.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Routines {

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Object genMonotonicUlid(
    Configuration configuration
  ) {
    GenMonotonicUlid f = new GenMonotonicUlid();

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Field<Object> genMonotonicUlid() {
    GenMonotonicUlid f = new GenMonotonicUlid();

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Object genUlid(
    Configuration configuration
  ) {
    GenUlid f = new GenUlid();

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Field<Object> genUlid() {
    GenUlid f = new GenUlid();

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Object timestampToUlid(
    Configuration configuration
    , LocalDateTime input
  ) {
    TimestampToUlid f = new TimestampToUlid();
    f.setInput(input);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Field<Object> timestampToUlid(
    LocalDateTime input
  ) {
    TimestampToUlid f = new TimestampToUlid();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Field<Object> timestampToUlid(
    Field<LocalDateTime> input
  ) {
    TimestampToUlid f = new TimestampToUlid();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Object timestamptzToUlid(
    Configuration configuration
    , OffsetDateTime input
  ) {
    TimestamptzToUlid f = new TimestamptzToUlid();
    f.setInput(input);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Field<Object> timestamptzToUlid(
    OffsetDateTime input
  ) {
    TimestamptzToUlid f = new TimestamptzToUlid();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Field<Object> timestamptzToUlid(
    Field<OffsetDateTime> input
  ) {
    TimestamptzToUlid f = new TimestamptzToUlid();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Integer ulidCmp(
    Configuration configuration
    , Object left
    , Object right
  ) {
    UlidCmp f = new UlidCmp();
    f.setLeft(left);
    f.setRight(right);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Integer> ulidCmp(
    Object left
    , Object right
  ) {
    UlidCmp f = new UlidCmp();
    f.setLeft(left);
    f.setRight(right);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Integer> ulidCmp(
    Field<Object> left
    , Field<Object> right
  ) {
    UlidCmp f = new UlidCmp();
    f.setLeft(left);
    f.setRight(right);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Boolean ulidEq(
    Configuration configuration
    , Object left
    , Object right
  ) {
    UlidEq f = new UlidEq();
    f.setLeft(left);
    f.setRight(right);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Boolean> ulidEq(
    Object left
    , Object right
  ) {
    UlidEq f = new UlidEq();
    f.setLeft(left);
    f.setRight(right);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Boolean> ulidEq(
    Field<Object> left
    , Field<Object> right
  ) {
    UlidEq f = new UlidEq();
    f.setLeft(left);
    f.setRight(right);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Object ulidFromUuid(
    Configuration configuration
    , UUID input
  ) {
    UlidFromUuid f = new UlidFromUuid();
    f.setInput(input);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Field<Object> ulidFromUuid(
    UUID input
  ) {
    UlidFromUuid f = new UlidFromUuid();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Field<Object> ulidFromUuid(
    Field<UUID> input
  ) {
    UlidFromUuid f = new UlidFromUuid();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Boolean ulidGe(
    Configuration configuration
    , Object left
    , Object right
  ) {
    UlidGe f = new UlidGe();
    f.setLeft(left);
    f.setRight(right);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Boolean> ulidGe(
    Object left
    , Object right
  ) {
    UlidGe f = new UlidGe();
    f.setLeft(left);
    f.setRight(right);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Boolean> ulidGe(
    Field<Object> left
    , Field<Object> right
  ) {
    UlidGe f = new UlidGe();
    f.setLeft(left);
    f.setRight(right);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Boolean ulidGt(
    Configuration configuration
    , Object left
    , Object right
  ) {
    UlidGt f = new UlidGt();
    f.setLeft(left);
    f.setRight(right);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Boolean> ulidGt(
    Object left
    , Object right
  ) {
    UlidGt f = new UlidGt();
    f.setLeft(left);
    f.setRight(right);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Boolean> ulidGt(
    Field<Object> left
    , Field<Object> right
  ) {
    UlidGt f = new UlidGt();
    f.setLeft(left);
    f.setRight(right);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Integer ulidHash(
    Configuration configuration
    , Object value
  ) {
    UlidHash f = new UlidHash();
    f.setValue(value);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Integer> ulidHash(
    Object value
  ) {
    UlidHash f = new UlidHash();
    f.setValue(value);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Integer> ulidHash(
    Field<Object> value
  ) {
    UlidHash f = new UlidHash();
    f.setValue(value);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Object ulidIn(
    Configuration configuration
    , Object input
  ) {
    UlidIn f = new UlidIn();
    f.setInput(input);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Field<Object> ulidIn(
    Object input
  ) {
    UlidIn f = new UlidIn();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Field<Object> ulidIn(
    Field<Object> input
  ) {
    UlidIn f = new UlidIn();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Boolean ulidLe(
    Configuration configuration
    , Object left
    , Object right
  ) {
    UlidLe f = new UlidLe();
    f.setLeft(left);
    f.setRight(right);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Boolean> ulidLe(
    Object left
    , Object right
  ) {
    UlidLe f = new UlidLe();
    f.setLeft(left);
    f.setRight(right);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Boolean> ulidLe(
    Field<Object> left
    , Field<Object> right
  ) {
    UlidLe f = new UlidLe();
    f.setLeft(left);
    f.setRight(right);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Boolean ulidLt(
    Configuration configuration
    , Object left
    , Object right
  ) {
    UlidLt f = new UlidLt();
    f.setLeft(left);
    f.setRight(right);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Boolean> ulidLt(
    Object left
    , Object right
  ) {
    UlidLt f = new UlidLt();
    f.setLeft(left);
    f.setRight(right);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Boolean> ulidLt(
    Field<Object> left
    , Field<Object> right
  ) {
    UlidLt f = new UlidLt();
    f.setLeft(left);
    f.setRight(right);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Boolean ulidNe(
    Configuration configuration
    , Object left
    , Object right
  ) {
    UlidNe f = new UlidNe();
    f.setLeft(left);
    f.setRight(right);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Boolean> ulidNe(
    Object left
    , Object right
  ) {
    UlidNe f = new UlidNe();
    f.setLeft(left);
    f.setRight(right);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<Boolean> ulidNe(
    Field<Object> left
    , Field<Object> right
  ) {
    UlidNe f = new UlidNe();
    f.setLeft(left);
    f.setRight(right);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Object ulidOut(
    Configuration configuration
    , Object input
  ) {
    UlidOut f = new UlidOut();
    f.setInput(input);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Field<Object> ulidOut(
    Object input
  ) {
    UlidOut f = new UlidOut();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type,
   * it may have been excluded from code generation. If this is a built-in
   * type, you can define an explicit {@link org.jooq.Binding} to specify how
   * this type should be handled. Deprecation can be turned off using
   * {@literal <deprecationOnUnknownTypes/>} in your code generator
   * configuration.
   */
  @Deprecated
  public static Field<Object> ulidOut(
    Field<Object> input
  ) {
    UlidOut f = new UlidOut();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static byte[] ulidToBytea(
    Configuration configuration
    , Object input
  ) {
    UlidToBytea f = new UlidToBytea();
    f.setInput(input);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<byte[]> ulidToBytea(
    Object input
  ) {
    UlidToBytea f = new UlidToBytea();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<byte[]> ulidToBytea(
    Field<Object> input
  ) {
    UlidToBytea f = new UlidToBytea();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static LocalDateTime ulidToTimestamp(
    Configuration configuration
    , Object input
  ) {
    UlidToTimestamp f = new UlidToTimestamp();
    f.setInput(input);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<LocalDateTime> ulidToTimestamp(
    Object input
  ) {
    UlidToTimestamp f = new UlidToTimestamp();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<LocalDateTime> ulidToTimestamp(
    Field<Object> input
  ) {
    UlidToTimestamp f = new UlidToTimestamp();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static UUID ulidToUuid(
    Configuration configuration
    , Object input
  ) {
    UlidToUuid f = new UlidToUuid();
    f.setInput(input);

    f.execute(configuration);
    return f.getReturnValue();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<UUID> ulidToUuid(
    Object input
  ) {
    UlidToUuid f = new UlidToUuid();
    f.setInput(input);

    return f.asField();
  }

  /**
   * @deprecated Unknown data type. Parameter type or return type is unknown.
   * If this is a qualified, user-defined type, it may have been excluded from
   * code generation. If this is a built-in type, you can define an explicit
   * {@link org.jooq.Binding} to specify how this type should be handled.
   * Deprecation can be turned off using {@literal
   * <deprecationOnUnknownTypes/>} in your code generator configuration.
   */
  @Deprecated
  public static Field<UUID> ulidToUuid(
    Field<Object> input
  ) {
    UlidToUuid f = new UlidToUuid();
    f.setInput(input);

    return f.asField();
  }
}
