-- 创建角色
CREATE ROLE engine_user LOGIN PASSWORD 'engine_user';

-- 创建模式
CREATE SCHEMA IF NOT EXISTS engine;

-- 模式级权限
GRANT USAGE, CREATE ON SCHEMA engine TO engine_user;

-- 当前所有表权限
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA engine TO engine_user;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA engine TO engine_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA engine TO engine_user;

-- 未来新表自动继承
ALTER DEFAULT PRIVILEGES IN SCHEMA engine GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO engine_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA engine GRANT USAGE, SELECT ON SEQUENCES TO engine_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA engine GRANT EXECUTE ON FUNCTIONS TO engine_user;

ALTER SCHEMA engine OWNER TO engine_user;
