/*
 * This file is generated by jOOQ.
 */
package com.zornflow.infrastructure.config.source.database.jooq.tables.records;


import com.zornflow.infrastructure.config.source.database.jooq.tables.pojos.RuleChains;

import java.time.OffsetDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RuleChainsRecord extends UpdatableRecordImpl<RuleChainsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>engine.rule_chains.id</code>.
     */
    public RuleChainsRecord setId(String value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>engine.rule_chains.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>engine.rule_chains.name</code>.
     */
    public RuleChainsRecord setName(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>engine.rule_chains.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>engine.rule_chains.version</code>.
     */
    public RuleChainsRecord setVersion(String value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>engine.rule_chains.version</code>.
     */
    public String getVersion() {
        return (String) get(2);
    }

    /**
     * Setter for <code>engine.rule_chains.description</code>.
     */
    public RuleChainsRecord setDescription(String value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>engine.rule_chains.description</code>.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>engine.rule_chains.created_at</code>.
     */
    public RuleChainsRecord setCreatedAt(OffsetDateTime value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>engine.rule_chains.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return (OffsetDateTime) get(4);
    }

    /**
     * Setter for <code>engine.rule_chains.updated_at</code>.
     */
    public RuleChainsRecord setUpdatedAt(OffsetDateTime value) {
        set(5, value);
        return this;
    }

    /**
     * Getter for <code>engine.rule_chains.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return (OffsetDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached RuleChainsRecord
     */
    public RuleChainsRecord() {
        super(com.zornflow.infrastructure.config.source.database.jooq.tables.RuleChains.RULE_CHAINS);
    }

    /**
     * Create a detached, initialised RuleChainsRecord
     */
    public RuleChainsRecord(String id, String name, String version, String description, OffsetDateTime createdAt, OffsetDateTime updatedAt) {
        super(com.zornflow.infrastructure.config.source.database.jooq.tables.RuleChains.RULE_CHAINS);

        setId(id);
        setName(name);
        setVersion(version);
        setDescription(description);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetTouchedOnNotNull();
    }

    /**
     * Create a detached, initialised RuleChainsRecord
     */
    public RuleChainsRecord(RuleChains value) {
        super(com.zornflow.infrastructure.config.source.database.jooq.tables.RuleChains.RULE_CHAINS);

        if (value != null) {
            setId(value.getId());
            setName(value.getName());
            setVersion(value.getVersion());
            setDescription(value.getDescription());
            setCreatedAt(value.getCreatedAt());
            setUpdatedAt(value.getUpdatedAt());
            resetTouchedOnNotNull();
        }
    }
}
