/*
 * This file is generated by jOOQ.
 */
package com.zornflow.infrastructure.config.source.database.jooq.tables.pojos;


import java.io.Serializable;
import java.time.OffsetDateTime;

import org.jooq.JSONB;


/**
 * 规则在链中的具体实例，存储顺序、与共享模板的链接以及属性覆盖
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class ChainRules implements Serializable {

    private static final long serialVersionUID = 1L;

    private final String id;
    private final String ruleChainId;
    private final String sharedRuleId;
    private final Integer sequence;
    private final String name;
    private final Integer priority;
    private final String condition;
    private final JSONB handlerConfig;
    private final OffsetDateTime createdAt;
    private final OffsetDateTime updatedAt;

    public ChainRules(ChainRules value) {
        this.id = value.id;
        this.ruleChainId = value.ruleChainId;
        this.sharedRuleId = value.sharedRuleId;
        this.sequence = value.sequence;
        this.name = value.name;
        this.priority = value.priority;
        this.condition = value.condition;
        this.handlerConfig = value.handlerConfig;
        this.createdAt = value.createdAt;
        this.updatedAt = value.updatedAt;
    }

    public ChainRules(
        String id,
        String ruleChainId,
        String sharedRuleId,
        Integer sequence,
        String name,
        Integer priority,
        String condition,
        JSONB handlerConfig,
        OffsetDateTime createdAt,
        OffsetDateTime updatedAt
    ) {
        this.id = id;
        this.ruleChainId = ruleChainId;
        this.sharedRuleId = sharedRuleId;
        this.sequence = sequence;
        this.name = name;
        this.priority = priority;
        this.condition = condition;
        this.handlerConfig = handlerConfig;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    /**
     * Getter for <code>engine.chain_rules.id</code>.
     */
    public String getId() {
        return this.id;
    }

    /**
     * Getter for <code>engine.chain_rules.rule_chain_id</code>.
     */
    public String getRuleChainId() {
        return this.ruleChainId;
    }

    /**
     * Getter for <code>engine.chain_rules.shared_rule_id</code>.
     */
    public String getSharedRuleId() {
        return this.sharedRuleId;
    }

    /**
     * Getter for <code>engine.chain_rules.sequence</code>.
     */
    public Integer getSequence() {
        return this.sequence;
    }

    /**
     * Getter for <code>engine.chain_rules.name</code>.
     */
    public String getName() {
        return this.name;
    }

    /**
     * Getter for <code>engine.chain_rules.priority</code>.
     */
    public Integer getPriority() {
        return this.priority;
    }

    /**
     * Getter for <code>engine.chain_rules.condition</code>.
     */
    public String getCondition() {
        return this.condition;
    }

    /**
     * Getter for <code>engine.chain_rules.handler_config</code>.
     */
    public JSONB getHandlerConfig() {
        return this.handlerConfig;
    }

    /**
     * Getter for <code>engine.chain_rules.created_at</code>.
     */
    public OffsetDateTime getCreatedAt() {
        return this.createdAt;
    }

    /**
     * Getter for <code>engine.chain_rules.updated_at</code>.
     */
    public OffsetDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        final ChainRules other = (ChainRules) obj;
        if (this.id == null) {
            if (other.id != null)
                return false;
        }
        else if (!this.id.equals(other.id))
            return false;
        if (this.ruleChainId == null) {
            if (other.ruleChainId != null)
                return false;
        }
        else if (!this.ruleChainId.equals(other.ruleChainId))
            return false;
        if (this.sharedRuleId == null) {
            if (other.sharedRuleId != null)
                return false;
        }
        else if (!this.sharedRuleId.equals(other.sharedRuleId))
            return false;
        if (this.sequence == null) {
            if (other.sequence != null)
                return false;
        }
        else if (!this.sequence.equals(other.sequence))
            return false;
        if (this.name == null) {
            if (other.name != null)
                return false;
        }
        else if (!this.name.equals(other.name))
            return false;
        if (this.priority == null) {
            if (other.priority != null)
                return false;
        }
        else if (!this.priority.equals(other.priority))
            return false;
        if (this.condition == null) {
            if (other.condition != null)
                return false;
        }
        else if (!this.condition.equals(other.condition))
            return false;
        if (this.handlerConfig == null) {
            if (other.handlerConfig != null)
                return false;
        }
        else if (!this.handlerConfig.equals(other.handlerConfig))
            return false;
        if (this.createdAt == null) {
            if (other.createdAt != null)
                return false;
        }
        else if (!this.createdAt.equals(other.createdAt))
            return false;
        if (this.updatedAt == null) {
            if (other.updatedAt != null)
                return false;
        }
        else if (!this.updatedAt.equals(other.updatedAt))
            return false;
        return true;
    }

    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((this.id == null) ? 0 : this.id.hashCode());
        result = prime * result + ((this.ruleChainId == null) ? 0 : this.ruleChainId.hashCode());
        result = prime * result + ((this.sharedRuleId == null) ? 0 : this.sharedRuleId.hashCode());
        result = prime * result + ((this.sequence == null) ? 0 : this.sequence.hashCode());
        result = prime * result + ((this.name == null) ? 0 : this.name.hashCode());
        result = prime * result + ((this.priority == null) ? 0 : this.priority.hashCode());
        result = prime * result + ((this.condition == null) ? 0 : this.condition.hashCode());
        result = prime * result + ((this.handlerConfig == null) ? 0 : this.handlerConfig.hashCode());
        result = prime * result + ((this.createdAt == null) ? 0 : this.createdAt.hashCode());
        result = prime * result + ((this.updatedAt == null) ? 0 : this.updatedAt.hashCode());
        return result;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ChainRules (");

        sb.append(id);
        sb.append(", ").append(ruleChainId);
        sb.append(", ").append(sharedRuleId);
        sb.append(", ").append(sequence);
        sb.append(", ").append(name);
        sb.append(", ").append(priority);
        sb.append(", ").append(condition);
        sb.append(", ").append(handlerConfig);
        sb.append(", ").append(createdAt);
        sb.append(", ").append(updatedAt);

        sb.append(")");
        return sb.toString();
    }
}
